name: "Epever2MQTT"
description: "Connects epever to MQTT"
version: "1.0.0"
slug: "epever2mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
devices:
  - /dev/ttyACM0
options:
  serialPort: /dev/ttyACM0
  baudRate: 115200
  flowControl: none
  parity: none
  char: 8
  stopBits: 1

  mqttServer: 127.0.0.1
  mqttPort: 1883
  mqttTopic: homeassistant
  mqttDevicename: epever
  mqttUsername: Mqtt
  mqttPassword:
  pollingInterval: 5
  verboseDebugging: false
schema:
  serialPort:
    type: string
    required: true
    default: /dev/ttyACM0
  baudRate:
    type: int
    required: true
    default: 115200
  flowControl:
    type: string
    required: true
    default: none
    options:
      - none # idk what options
  parity:
    type: string
    required: true
    default: none
    options:
      - none # idk what options
  char:
    type: int
    required: true
    default: 8
  stopBits:
    type: int
    required: true
    default: 1
  mqttServer:
    type: string
    required: true
    default: 192.168.1.3
  mqttPort:
    type: int
    required: true
    default: 1883
  mqttTopic:
    type: string
    required: true
    default: homeassistant
  mqttDevicename:
    type: string
    required: true
    default: epever
  mqttUsername:
    type: string
    required: true
    default: Mqtt
  mqttPassword:
    type: string
    required: true
    default: ekujgn43489hefniu34n897h
  pollingInterval:
    type: int
    required: true
    default: 5
  verboseDebugging:
    type: boolean
    required: true
    default: false