# Configuration for EPEver Serial Device
############################################################

# Serial config for the Tracer Device...
serialPort: /dev/ttyACM0
baudRate: 115200
flowControl: none
parity: none
char: 8
stopBits: 1

# Home Assistant MQTT server:
mqttServer: 127.0.0.1
mqttPort: 1883
mqttTopic: homeassistant
mqttDevicename: epever
mqttUsername:
mqttPassword:

# Core Program Config...

# How often poll for data (in seconds)
pollingInterval: 5
verboseDebugging: false # set to true to debug sensor values in log.
